services:
  core:
    image: ubuntu:20.04
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    depends_on:
      - sql
  sql:
    build:
      context: .
    ports:
      - 1433:1433