services:
  core:
    image: mcr.microsoft.com/devcontainers/dotnet:7.0-jammy
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    depends_on:
      - sql
  sql:
    build:
      context: .
    ports:
      - 1433:1433